/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Igra;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DataBaseProxy;

/**
 *
 * @author stefa
 */
public class GlavniProzor extends javax.swing.JFrame {
    Igra igr;
    DataBaseProxy db;
    /**
     * Creates new form Mastermind
     */
    public GlavniProzor() {
        initComponents();
        igr = new Igra();
        db = new DataBaseProxy();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slagalica");
        setBackground(new java.awt.Color(0, 102, 204));
        getContentPane().setLayout(null);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 10, 480, 30);

        jButton1.setText("Učitaj Igru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 470, 460, 30);

        jButton2.setText("Sačuvaj Igru");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 530, 480, 30);

        jButton3.setText("Predajem Se");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 490, 480, 30);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setLabelFor(jTextField1);
        jLabel1.setText("-");
        jLabel1.setName("error"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 390, 16);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pokušaj", "Pogođeno"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 50, 480, 430);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datum", "Igrac"
            }
        ));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(540, 10, 460, 430);

        setSize(new java.awt.Dimension(1034, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int row = jTable1.getSelectedRow();
       igr = db.loadGame(jTable1.getValueAt(row, 0).toString(),jTable1.getValueAt(row, 1).toString());
       DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
       dtm.setRowCount(0);
       igr.test();
       dtm.addRow(new Object []{igr.pokusaj+"",igr.pogodjeno[0]+":"+igr.pogodjeno[1]});
       igr.pogodjeno[0] = 0;
       igr.pogodjeno[1] = 0;
       jTable2.setModel(dtm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       if(evt.getKeyCode()==10)
       {
           try
           {
               if(Integer.parseInt(jTextField1.getText())<1000 || Integer.parseInt(jTextField1.getText())>=10000)
                {
                    jLabel1.setText("Unesite odgovarajuci cetvorocifreni broj");
                    jTextField1.setText("");
                }
               else
               {
                   igr.pokusaj = Integer.parseInt(jTextField1.getText());
                   igr.test();
                   if(igr.pogodjeno[0] == 4)
                   {
                       JOptionPane.showMessageDialog(null,"POBEDILI STE!!!", "SVAKA CAST", JOptionPane.INFORMATION_MESSAGE);
                       Igra igr = new Igra();
                       ((DefaultTableModel)jTable2.getModel()).setRowCount(0);
                       jTextField1.setText("");
                   }
                   else
                   {
                   DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
                   dtm.addRow(new Object[]{igr.pokusaj+"", "Tacno mesto: "+igr.pogodjeno[0]+" Pogresno mesto: "+igr.pogodjeno[1]});
                   igr.pogodjeno[0] = 0;
                   igr.pogodjeno[1] = 0;
                   jTable2.setModel(dtm);
                   jTextField1.setText("");
                   }
               }
               
           }
           catch(Exception ex)
           {
               jLabel1.setText("Unesite odgovarajuci cetvorocifreni broj");
               System.out.println("err"+ ex);
               jTextField1.setText("");
           }
           
       }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        igr = new Igra();
        DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
        dtm.setRowCount(0);
        jTable2.setModel(dtm);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String usr = "";
        if(igr.user == "")
       {
        usr = JOptionPane.showInputDialog("Unesite Vase ime: ");
       }
        System.out.println(igr.user);
       if(usr != null)
       {
       igr.user = usr;
       db.saveGame(igr);
       populate();
       ((DefaultTableModel)jTable2.getModel()).setRowCount(0);
       igr = new Igra();
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniProzor().setVisible(true);
            }
        });
    }
    public void populate()
    {
      ArrayList<String> games = db.getPrevGames();
      DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
      dtm.setRowCount(0);
      for(String game : games)
      {
          System.out.println(game);
          String[] deo = game.split(",");
          dtm.addRow(new Object[]{deo[0],deo[1]});
      }
      jTable1.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
